version: 2
updates:
  - package-ecosystem: "npm"
    directory: "/packages/theme"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "08:00"
      timezone: "Australia/Sydney"
    open-pull-requests-limit: 5
    groups:
      npm-minor-and-patch:
        applies-to: "version-updates"
        update-types:
          - "minor"
          - "patch"
